### PR TITLE
Added JOURNAL option for log_file

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by lzap** [comment]
Great, I was expecting you wanting me to add parameters for all the new configuration values. They are not that useful in my eyes, I was thinking a simple idea for these kind of "detailed" config values which don't necessary need to be exposed via puppet.

How about creating `settings-override.yaml` for both core and proxy, anything defined in there overrides `settings.yaml`. The file would be unmanaged, something like for ad-hoc configuration changes (e.g. temporary changes). But I think you won't like this, it can create confusion indeed :-)

**Comment by ekohl** [comment]
I'm strongly against an unmanaged file. If we expect users to be able to use these options then indeed they should be parameters.

**Comment by mmoll** [comment]
Bringing this in, as the default will stay as-is (logfile).

**Comment by mmoll** [comment]
merged, díky @lzap!

**Pull request merged**
