### PR TITLE
Configure ansible's stdout_callback to yaml for nicer output

### PR DESCRIPTION
**Pull request by iNecas**
Before:

ansible-stdout-before

After:

ansible-stdout-after

### CODE REVIEW

**Comment by iNecas** [comment]
For some reason, I see `stdout_lines` in output by foreman, while when running from command line, I see `stdout_lines: <omitted>`, which makes the output even nicer. Not sure if that's something related to my local setup. Anyway, I still think the output is much nicer than the default one.

**Comment by ares** [comment]
LGTM, if no one objects, I'll merge :-) the output is definitely more readable

**Comment by ekohl** [comment]
We use the same one in forklift. The only downside there is that commands that have colors show the literal escape codes. Not sure if here you'd have the same problem.

**Comment by iNecas** [comment]
We have support for color codes in foreman_ansible, so that should be fine

**Comment by ekohl** [comment]
Thanks!

**Comment by ares** [comment]
Thanks @iNecas, merging!

**Comment by ares** [comment]
oh lol, github page didn't reload until I wrote a comment, then realized it's already merged, so thanks also @ekohl :-)

**Pull request merged**
