### PR TITLE
Fixes #31430 - use correct key and server for ansible-runner deb

### PR DESCRIPTION
**Pull request by evgeni**
(cherry picked from commit af2656f8ff58626c0f907d06e33856d36ee663f6)

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by evgeni** [comment]
also picked the test fix for docker :roll_eyes:

**Comment by evgeni** [comment]
@ekohl I don't see where the last two Acceptance errors come from :(

**Comment by evgeni** [comment]
But it's equally broken in master: https://github.com/theforeman/puppet-foreman_proxy/runs/1868649624?check_suite_focus=true

**Comment by ekohl** [comment]
The "fun" thing is that it does pass locally for me in a vagrant VM ... I opened https://github.com/theforeman/puppet-foreman_proxy/pull/647 to see if that helps.

**Pull request merged**
