### PR TITLE
Add tftp_manage_wget param to make installing wget optional

### LINKED ISSUE #198: Managing wget package causes conflicts with existing packages
https://github.com/theforeman/puppet-foreman_proxy/blob/master/manifests/tftp.pp#L32

By managing the wget package unconditionally, foreman_proxy::tftp cannot be used in environments that  already manage the wget package.

### PR DESCRIPTION
**Pull request by brandonweeks**
Resolves #198. I couldn't find a way to test this with rspec since the package is added via a function, if I missed something let me know and I'll add the tests.

### CODE REVIEW

**Comment by ekohl** [comment]
Mind adding a ```validate_bool``` check for it? Other than that it looks good.

**Comment by mmoll** [comment]
In theforeman-dns we also use ensure_packages and test if the catalogue contains that package, so that should work here also.

**Comment by brandonweeks** [comment]
@mmoll thanks for the conformation that should work, there was actually a typo in the code preventing the test from passing. Doh!

The commit has been amended with tests and the validation.

**Comment by mmoll** [comment]
:+1:

**Comment by ekohl** [comment]
Thanks!

**Pull request closed without merging**
