### PR TITLE
Remove cache_data and random_password in favor of those in extlib

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks good, but the tests won't pass until we fix this in the foreman module.

**Comment by domcleal** [comment]
:+1: once the other's merged.

**Comment by domcleal** [comment]
Could you rebase this please and also update usage in manifests/plugin/dns/powerdns/params.pp?  It was added just now in caf8f91, but otherwise looks green once that's done.

**Comment by domcleal** [comment]
Should we set the minimum theforeman/foreman version in metadata.json to 5.0.0 too, or just extend it to `< 6.0.0`?  librarian-puppet just failed to combine the master branches of both since I bumped the version.

The minimum may make sense given it's required now that we depend on extlib *instead* of puppet-foreman.

**Comment by ekohl** [comment]
We still rely on puppet-foreman for the repos, so a minimum version of 5.0.0 is needed.

**Comment by ehelms** [comment]
I updated the metadata to change the foreman requirement to > 5.0.0

**Comment by ekohl** [comment]
:+1:

**Comment by domcleal** [comment]
@ehelms could you also fix the instance in powerdns' params please?

**Comment by ehelms** [comment]
Ahh right, forgot about that comment, should be updated now

**Comment by domcleal** [comment]
:+1: thanks

**Comment by domcleal** [comment]
Merged, thanks @ehelms.

**Pull request merged**
