### PR TITLE
Feature/8942 tftp root param override

### PR DESCRIPTION
**Pull request by gpetras**

### CODE REVIEW

**Comment by gpetras** [comment]
Can someone re-test this? I added some commits and rebased. Should be good now.

**Comment by mmoll** [comment]
this needs theforeman/puppet-tftp#25 to fo in first

**Comment by gpetras** [comment]
Yup, thanks @mmoll!

**Comment by mmoll** [comment]
Restarted tests, all is :green_heart:
:+1:

**Comment by domcleal** [comment]
Thanks @gpetras!

**Pull request closed without merging**
