### PR TITLE
add dhcp_search_domains parameter

### PR DESCRIPTION
**Pull request by lbischof**
I added a dhcp_search_domains parameter. I didn't write any tests because I don't know how.

### CODE REVIEW

**Comment by domcleal** [comment]
:+1: looks fine to me.

If you did want to try writing a test, it should be straight forward with the examples already there.  spec/classes/foreman_proxy__proxydhcp__spec.rb would be the file, you'd create a new context block, e.g. `context 'with dhcp_search_domains' do`, set the parameter on the class in the pre_condition block and then have a `it { should contain_dhcp__pool('example.com').with_search_domains(...) }`.

**Comment by lbischof** [comment]
Great thanks. I'll try writing a test over the weekend.

**Comment by lbischof** [comment]
I added a test.

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
