### PR TITLE
Refs #21006 - Workaround broken grub2 on EL7.4

### PR DESCRIPTION
**Pull request by ekohl**
Backport of https://github.com/theforeman/puppet-foreman_proxy/pull/374.

### CODE REVIEW

**Comment by lzap** [comment]
Which version should this apply to? I am on Katello 3.4 and this does not apply cleanly:

```
[root@nuc foreman_proxy]# patch -p1 < 376.patch 
patching file manifests/tftp.pp
Hunk #3 FAILED at 72.
1 out of 3 hunks FAILED -- saving rejects to file manifests/tftp.pp.rej
[root@nuc foreman_proxy]# pwd
/usr/share/foreman-installer/modules/foreman_proxy
```

**Comment by ekohl** [comment]
That's because 3.4 doesn't include b4c47206d0e2c32179eb2e1b3d00933d97a634ad yet. It might require some manual fixing to apply it then.

**Comment by lzap** [comment]
Ok finally testing :-) thanks.

```
[root@nuc foreman_proxy]# patch -p1 < b4c47206d0e2c32179eb2e1b3d00933d97a634ad.patch 
patching file manifests/tftp.pp
[root@nuc foreman_proxy]# patch -p1 < 376.patch 
patching file manifests/tftp.pp
```

**Comment by lzap** [comment]
The EFI file works in libvirt with EDK2 git loader.

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
