### PR TITLE
refs #9449 - drop usage of lsb fact

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ekohl** [comment]
This module no longer supports EL5 so in https://github.com/theforeman/puppet-foreman_proxy/pull/153 I dropped it.

**Comment by ekohl** [comment]
I stand corrected, I dropped the support somewhere else but you can apply the same logic here.

**Comment by mmoll** [comment]
even better, thanks for the hint :bow:

**Comment by ekohl** [comment]
:+1:

**Comment by mmoll** [comment]
Squashed the commits, I somehow messed up while rebasing.

**Comment by domcleal** [comment]
Thanks @mmoll!

**Pull request closed without merging**
