### PR TITLE
Contain classes

### PR DESCRIPTION
**Pull request by ekohl**
This is the current method of containing classes.

### CODE REVIEW

**Comment by mmoll** [comment]
@ekohl pre-test checks fail currently...

**Comment by mmoll** [comment]
Ah, missing modulesync...

**Comment by mmoll** [comment]
could you add the deletion of that puppet-lint plugin to this PR?

**Comment by ekohl** [comment]
Updated

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
