### PR TITLE
modulesync: enable future parser tests

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by domcleal** [comment]
I think that's fixed now, subject to https://github.com/theforeman/puppet-dns/pull/31 (WIP) https://github.com/theforeman/puppet-tftp/pull/29 (ok).

**Comment by mmoll** [comment]
:+1:

**Comment by ekohl** [comment]
Rebased. Will merge when the tests are green.

**Comment by mmoll** [comment]
merged, thanks!

**Pull request merged**
