### PR TITLE
Enforce external Dynflow core on Debian based distibutions 

### PR DESCRIPTION
**Pull request by adamruzicka**
Follows (and includes) https://github.com/theforeman/puppet-foreman_proxy/pull/512

### CODE REVIEW

**Comment by mmoll** [comment]
@adamruzicka :point_up:

**Comment by adamruzicka** [comment]
Rebased, sorry for the delay

**Comment by mmoll** [comment]
@adamruzicka Is this still needed?

**Comment by adamruzicka** [comment]
It is not strictly *needed*, but it would bring the two platforms closer to each other by using separate smart_proxy_dynflow_core on both

**Comment by mmoll** [comment]
@adamruzicka Could you rebase this PR? I guess https://github.com/theforeman/foreman-packaging/pull/4196 is needed for this?

**Comment by adamruzicka** [comment]
Right, will get to this eventually. This is not related to that packaging PR at all. This is about how smart proxy dynflow core is deployed. The packaging PR is recommended for running dynflow with sidekiq

**Comment by ezr-ondrej** [comment]
We probably want to close this now, right? :)

**Comment by ekohl** [comment]
Yes we do. Thanks!

**Pull request closed without merging**
