### PR TITLE
Set foreman_smartproxy features for built-in and plugin modules

### PR DESCRIPTION
**Pull request by domcleal**
Uses datacat to generate an array of enabled features across built-in
and plugin modules by passing the feature name to settings_file, or
using the foreman_proxy::feature type.

### CODE REVIEW

**Comment by ekohl** [comment]
I had expected the ```$feature``` parameter on ```foreman_proxy::plugin```. Any reason you chose ```foreman_proxy::settings_file```?

**Comment by domcleal** [comment]
> I had expected the $feature parameter on foreman_proxy::plugin. Any reason you chose foreman_proxy::settings_file?

Yes, I begin developing with it on foreman_proxy::plugin and then moved it because settings_file has better knowledge of whether the module is enabled or not. It's possible to include a plugin class, which uses foreman::plugin, but then configure the module to be disabled. It's also shared between plugins and built-in modules.

**Comment by ekohl** [comment]
You're right, built in modules don't use the plugin define.

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
