### PR TITLE
Add Puppet 8 support

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Please rebase.

**Comment by bastelfreak** [comment]
@ekohl done

**Comment by ekohl** [comment]
Needs https://github.com/voxpupuli/voxpupuli-acceptance/pull/75

**Comment by bastelfreak** [comment]
restarted it again

**Comment by ekohl** [comment]
I did a puppet-foreman_scap_client 1.0.0 release and I'll fix up packaging during the update.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/9955

**Comment by ekohl** [comment]
I'll still need to bump puppetlabs-stdlib

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/9964

**Review by ekohl — APPROVED** [review]
This should now pass.

**Pull request merged**
