### PR TITLE
Fixes #20721 - use in-memory sqlite in smart proxy dynflow

### PR DESCRIPTION
**Pull request by iNecas**
The persisted sqlite is not suitable for large scale that
is being used by remote execution.

### CODE REVIEW

**Comment by ehelms** [comment]
What do you think about updating at least https://github.com/theforeman/puppet-foreman_proxy/blob/5b1e2e4bea5a09a32f0aa74f787b139616722441/manifests/plugin/dynflow.pp#L7 to indicate no path means use in memory database? I think that is a subtle thing that can easily be overlooked by someone.

**Comment by iNecas** [comment]
@ehelms better?

**Comment by ekohl** [comment]
I think @mmoll suggested this might need a migration in the installer if you want to apply this to existing answer files and I think that is what we want, correct?

**Comment by iNecas** [comment]
It does not need it because this param s not saved in answer file, but the class is included in other modules

**Comment by ekohl** [comment]
> It does not need it because this param s not saved in answer file, but the class is included in other modules

foreman-installer does expose it: https://github.com/theforeman/foreman-installer/blob/0fdee2dd246ebb513cddff7527e30f28cde7380e/config/foreman-answers.yaml#L60

**Comment by iNecas** [comment]
But it doesn't store the default params in answer file by default. The option is there just in case people want to actualy change some params, but in that case we should provably not migrate their choices. This is quite big edgecase I'm not sure is worth it.

**Pull request merged**
