### PR TITLE
Fixes #7833 - foreman_url is set for the smart proxy

### PR DESCRIPTION
**Pull request by lzap**
Need this for various plugins.

### CODE REVIEW

**Comment by lzap** [comment]
Pushed with unit test and reordered as requested.

**Comment by ekohl** [comment]
Looks like it needs a rebase.

**Comment by lzap** [comment]
Oh missed that, refreshed.

**Comment by domcleal** [comment]
:+1:

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
