### PR TITLE
update (server_)vardir parameter from puppet-puppet

### PR DESCRIPTION
**Pull request by mmoll**
needed after theforeman/puppet-puppet#241 got merged

### CODE REVIEW

**Comment by ekohl** [comment]
:+1:

**Comment by domcleal** [comment]
Could you bump the min version of puppet-puppet in metadata.json please?

**Comment by mmoll** [comment]
There we go: theforeman/puppet-puppet#243

**Comment by domcleal** [comment]
Sorry, I mean the metadata.json in this repo to say we depend on >= 3.0.0.

**Comment by domcleal** [comment]
:+1:

**Comment by ekohl** [comment]
:+1:

**Comment by domcleal** [comment]
Thanks!

**Pull request merged**
