### PR TITLE
Fixes #13024 - Should create dirs for ZTP and POAP files

### PR DESCRIPTION
**Pull request by fernandocarolo**
This patch ensures that the directories used for storing ZTP and POAP config files are created when the TFTP proxy is installed.

### CODE REVIEW

**Comment by mmoll** [comment]
@fraenki what do you think?

**Comment by fraenki** [comment]
@mmoll TBH I can't tell, because I no longer have access to any ZTP/POAP device.

**Comment by mmoll** [comment]
allright, I also don't use ZTP/POAP but think this is good :+1:

**Comment by ekohl** [comment]
I don't mind this, but do we actually have automatic downloading of ZTP/POAP? I recall those were manual operations anyway. Then again, this doesn't hurt so :+1:

**Comment by fernandocarolo** [comment]
@ekohi there is no automatic downloading of ZTP or POAP binaries, but those directories are used to store ZTP/POAP boot scripts created from templates, similar to the PXE scripts that are saved under pxelinux.cfg. Besides that, the DHCP proxy relies on those directory names to select the appropriate set of extra DHCP options that should be configured for a lease when it is used by a host running JunOS or NX-OS.

**Comment by ekohl** [comment]
@fernandocarolo makes sense. Thanks!

**Pull request closed without merging**
