### PR TITLE
Add acceptance tests

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
please update the spec tests :)

**Comment by ekohl** [comment]
Updated the tests.

**Comment by mmoll** [comment]
more updates seem to be required ;)

**Comment by ekohl** [comment]
So it looks like there's a typo in the RPM spec.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/2378

**Comment by ekohl** [comment]
And https://github.com/theforeman/foreman-packaging/pull/2379 for good measure.

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
