### PR TITLE
Compatible with theforeman/dns 2.0.0

### PR DESCRIPTION
**Pull request by domcleal**
I think our usage in foreman_proxy::proxydns is just fine with 2.0.0.

### CODE REVIEW

**Comment by ekohl** [comment]
Clearly not since the tests blew up :(

**Comment by domcleal** [comment]
Haha, great.

**Comment by domcleal** [comment]
The remaining test failure is kind of interesting.  We allow the user to specify the dns_zone, but not to override the SOA, which is always the FQDN.  This potentially results in them creating a zone with an SOA outside the zone, which puppet-dns now detects.

Maybe we should change the default SOA of the forward zone to be the shortname of the host, plus the zone name?

**Comment by ekohl** [comment]
I'll have a look at puppet-dns because maybe the SOA check doesn't have to be there.

**Comment by domcleal** [comment]
Yeah, are we overloading the parameter?  The SOA record itself can refer to an external name, but since we also add an A record to the zone itself for the SOA, we assume/require that it's also inside that zone.

**Comment by ekohl** [comment]
As said on IRC, I think the check for SOA to be inside the zone is wrong and should be removed from puppet-dns until we come up with a better solution.

**Comment by mmoll** [comment]
opened theforeman/puppet-dns#29

**Comment by domcleal** [comment]
Thanks @mmoll, tested are now passing in this PR.

**Comment by ekohl** [comment]
:+1:

**Comment by mmoll** [comment]
merged as fb681ba, thanks @domcleal!

**Pull request closed without merging**
