### PR TITLE
Use modern defaults and document compatibility

### PR DESCRIPTION
**Pull request by ekohl**
We can assume new installations. Users of older versions should read the
notes on compatibility.

### CODE REVIEW

**Comment by mmoll** [comment]
If we can delete old code, we should do it now ;)

**Comment by ekohl** [comment]
So you're saying we should remove these options and just use the new code?

**Comment by mmoll** [comment]
At least what's possible, I don't remember if the promise of the puppet mdoules was one or two old releases backwards compatibility, but 1.14 is old enough to let go for sure.

**Comment by ekohl** [comment]
You're right, typically we've done n-2. This time I think it's too early for a major version bump so I'd rather keep it in so we can do a minor version bump.

**Comment by mmoll** [comment]
Isn't that change in defaults also a major version bump?

**Comment by ekohl** [comment]
I think you have me there :)

**Comment by ekohl** [comment]
Updated to drop 1.15 and older.

**Comment by mmoll** [comment]
@ekohl check out the test failures

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
