### PR TITLE
use moved foreman::repos define

### PR DESCRIPTION
**Pull request by mmoll**
to be merged after theforeman/puppet-foreman#404

### CODE REVIEW

**Comment by domcleal** [comment]
Could you also update the dependency in metadata.json?  Perhaps it's a good idea in the puppet-foreman PR to change the current (master) version to 5.2.0, then depend on >= 5.2.0 here too.

**Comment by mmoll** [comment]
updated

**Comment by domcleal** [comment]
:+1: when tests pass.

**Comment by ekohl** [comment]
:+1: when tests pass

**Comment by mmoll** [comment]
tests passed ;)

**Comment by domcleal** [comment]
Thanks @mmoll!

**Pull request merged**
