### PR TITLE
Refactor plugin parameter handling

### PR DESCRIPTION
**Pull request by ekohl**
When all values are static, there's no need to load it via a params class. It also tightens some parameter types.

### CODE REVIEW

**Comment by mmoll** [comment]
@ekohl tests fail

**Comment by mmoll** [comment]
@ekohl needs a rebase ;)

**Comment by ekohl** [comment]
Rebased. Also includes some spec improvements as separate commits to speed up the testing.

**Comment by mmoll** [comment]
Fails on Puppet 5 :broken_heart:

**Comment by ekohl** [comment]
Looks like this reduces the unit test time from 21 to 26 minutes (https://travis-ci.org/theforeman/puppet-foreman_proxy/builds/629474276) to 6 to 7 minutes (https://travis-ci.org/theforeman/puppet-foreman_proxy/builds/629687391).

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
