### PR TITLE
Fixes #33688 - Set max_files to unlimited for TFTP directories

### PR DESCRIPTION
**Pull request by thomas-merz**
Announcement of "Enhancement" see here: https://puppet.com/docs/puppet/6/release_notes_puppet.html#enhancements_puppet_x_23_0-PUP-10946

### CODE REVIEW

**Review by wbclark — COMMENTED** [review]
Thank you @thomas-merz , the code change looks good to me, and I'm glad it worked to suppress the warnings in your environment.

I created an issue for this over on the Foreman community Redmine instance at https://projects.theforeman.org/issues/33688 to have better tracking

Could you kindly update the commit message and PR title to:

`Fixes #33688 - Set max_files to unlimited for TFTP directories`

Going forward I'll be away for about a week, so I'll ask @ekohl if he is willing to finish reviewing this while I am gone.

**Comment by thomas-merz** [comment]
Hi @wbclark , I changed the PR title 👍 
Hi @ekohl , could you please review this? Thanks!

**Comment by thomas-merz** [comment]
@ekohl , you are absolutely right - I reflected this also in `metadata.json`.

**Review by ekohl — APPROVED** [review]
We'll need to reflect this change here:
https://github.com/theforeman/foreman-installer/blob/b75531bcd1ff183837d06a1c02f065a1642764af/spec/puppet_version_spec.rb#L5
https://github.com/theforeman/foreman-packaging/blob/ae6126cdd34bb80255b480727766cefebac5ef5c/packages/foreman/foreman-installer/foreman-installer.spec#L21
https://github.com/theforeman/foreman-packaging/blob/64f9b0fdff88d5990af99c5202f3a06b07532798/debian/buster/foreman-installer/control#L18
https://github.com/theforeman/foreman-packaging/blob/64f9b0fdff88d5990af99c5202f3a06b07532798/debian/focal/foreman-installer/control#L18

I now started the tests to verify this passes.

**Comment by ekohl** [comment]
Looks like I missed that there were emoji's in the commit message. IMHO we should make a check to disallow those.

**Comment by thomasmerz** [comment]
I use these emojis often because "using emojis on commit messages provides an easy way of identifying the purpose or intention of a commit with only looking at the emojis used" (https://github.com/carloscuesta/gitmoji). But I'm also fine if we don't want use them in "The Foreman" Project.

**Comment by thomas-merz** [comment]
I use these emojis often because "using emojis on commit messages provides an easy way of identifying the purpose or intention of a commit with only looking at the emojis used" (https://github.com/carloscuesta/gitmoji). But I'm also fine if we don't want use them in "The Foreman" Project.

**Pull request merged**
