### PR TITLE
Fixes #21006 - Enable workaround for broken grub2 in EL7.4

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ace13** [comment]
On our CentOS 7.4 TFTP server, there's no `grub-mkimage`, only `grub2-mkimage`.

Apart from that, creating a `grubx64.efi` file with this change does result in something that you can PXE boot with.

**Comment by ekohl** [comment]
@ace13 thanks for testing, I lacked the environment to do so. Updated

**Comment by mmoll** [comment]
Does the Enum ` $grub_installation_type` need an update here?

**Comment by ekohl** [comment]
> Does the Enum $grub_installation_type need an update here?

Done

**Comment by lzap** [comment]
Tried but was unable to test, will do on Monday.

**Comment by ekohl** [comment]
[Implement grub workarounds in EL 7.4](https://trello.com/c/kzq2dHOn/509-implement-grub-workarounds-in-el-74)

**Comment by ekohl** [comment]
Did a pipeline test and it executes correctly now but I don't know how to verify the produced image.

**Comment by lzap** [comment]
I am unable to locate `netboot.pp` file on Katello 3.4 or Satellite 6.3. This was refactored recently and this PR does not apply cleanly. What is the best approach to test this? I'd rather test final code.

Or if you can give me the exact command the puppet exec generates, I can just execute that and test EFI booting with that.

**Comment by lzap** [comment]
Provisioning nightly foreman to do the test.

**Comment by ekohl** [comment]
@lzap I'll work on a backport. Let me know if this works.

**Comment by lzap** [comment]
The backport works fine, thanks a bunch.

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
