### PR TITLE
Add dir for corrupted openscap reports

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
@xprazak2 tests need updating too

**Comment by xprazak2** [comment]
I updated the tests, everything is green now.

**Comment by ares** [comment]
This will work with https://github.com/theforeman/smart_proxy_openscap/pull/44 and new smart_proxy_openscap release (0.6.2) but is backwards compatible so can be included even before the release.

**Comment by ares** [comment]
sure, that's fine too :-)

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
