### PR TITLE
Listen on IPv6 by default

### PR DESCRIPTION
**Pull request by ekohl**
This enables running in an IPv6-only setup.

### CODE REVIEW

**Comment by mmoll** [comment]
iirc the main problem was that this default would break Windows and/or FreeBSD, I'll check at least with FreeBSD later.

**Comment by ekohl** [comment]
Would it be an idea to only do this on Linux then?

**Comment by mmoll** [comment]
What's working under FreeBSD is `['0.0.0.0', '::']`, could you check if that also would work on Linux?

**Comment by ekohl** [comment]
That doesn't work on my EL7 system. After a bit of searching I did find https://github.com/ruby/ruby/commit/b1f493dcd1092fe17cccec998e175516ed5c6e47 which I think means that only Ruby 2.1 and higher this works. You can use ```sysctl net.ipv6.bindv6only=1``` and then your suggestion should work.

Later I'll try to reproduce this on a newer Ruby but I'm leaning to considering this invalid and closing.

**Comment by ekohl** [comment]
Confirmed that Ruby 2.3 does listen on both IPv4 and IPv6 when binding to ```*```.

**Pull request closed without merging**
