### PR TITLE
refs #21350 - installer support for disable_tls_versions

### PR DESCRIPTION
**Pull request by stbenjam**
Needs https://github.com/theforeman/smart-proxy/pull/559

### CODE REVIEW

**Comment by stbenjam** [comment]
@ekohl That would be useful, wouldn't it? Updated.

**Comment by stbenjam** [comment]
Proxy side is merged

**Comment by ekohl** [comment]
And a good morning to me. Shall I squash the commits while merging?

**Comment by stbenjam** [comment]
Yes please

**Comment by mmoll** [comment]
merged, thanks @stbenjam!

**Comment by stbenjam** [comment]
Thanks!

**Pull request merged**
