### PR TITLE
Per-provider DNS configuartion files

### PR DESCRIPTION
**Pull request by ekohl**
Initial work to split the DNS config. Untested and it doesn't manage the settings files.

### CODE REVIEW

**Comment by ekohl** [comment]
Now with a README for compatibility and modified rspec tests. Haven't done tests on an actual system and a test with ```dns_split_config_files = false``` would be great as well.

**Comment by domcleal** [comment]
Looks and appears to work fine for me, thanks!  There's a typo in the commit message though, "configuration".

It also seems our tests are going to be dependent on the fixes in #184 around r-p-f and sudoers, else we split that out?

**Comment by ekohl** [comment]
> Looks and appears to work fine for me, thanks! There's a typo in the commit message though, "configuration".

Will fix

> It also seems our tests are going to be dependent on the fixes in #184 around r-p-f and sudoers, else we split that out?

I think that's a good idea because currently master is broken.

**Comment by mmoll** [comment]
#193 will fix the test failures in master

**Comment by mmoll** [comment]
This is looking good, merged!
bedankt @ekohl!

**Pull request merged**
