### PR TITLE
Add puppet_use_cache parameters

### PR DESCRIPTION
**Pull request by mmoll**
from master branch

### CODE REVIEW

**Comment by domcleal** [comment]
We'd call that 2.3.0 if it's adding new parameters.  Which I'm not against releasing :)

**Comment by mmoll** [comment]
hm, OK... then we might as well use master for that :)

**Comment by domcleal** [comment]
Yep.  The only thing we might want to do first is release the DHCP and DNS modules with bumped versions (think we said they should be major bumps due to concat change) and bump the acceptable version ranges in this module.

**Comment by domcleal** [comment]
And fix fixtures.yml to load the right concat...

**Pull request closed without merging**
